# Generated by Django 4.2.4 on 2023-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_selctionofcommittee_represantative_applicationid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelctionOfCommittee',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
            ],
        ),
    ]
